### ISSUE TITLE
Erg jammer

### ISSUE THREAD

**Issue by SilvanDomino** [DarrenVs/MultiplayerJavascriptFramework#7]
Je hebt feedback gekregen van **SilvanDomino**
URL: https://github.com/DarrenVs/MultiplayerJavascriptFramework/blob/master/

Feedback: Je hebt ongelovelijk veel een mooie code geschreven. Daar moet je zeker trots op zijn. Het is alleen zeer jammer dat je geen opdracht hebt gemaakt. Je bent verder gegaan met jouw vorige proefopdracht, niet een nieuwe.

Normaal ben ik erg soepel met nakijken, en je programmeer werk is erg goed. Je hebt alleen geen nieuwe proefopdracht ingeleverd.[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/)

**Comment by DarrenVs** [comment]
De opdracht was een server maken, Ik heb gebruik gemaakt van mijn vorige project wat inderdaad mijn canvas framework was. Maar dit project ging om de server functionaliteit.

Over het functionaliteit gesproken, op een eerdere 'Issue' werd mij verteld dat niets werkten daarom heb ik nu een README toegevoegd zodat je in stappen kan volgen hoe je de server aan zet.

Ik zal hem later weer online hosten zodra mijn thuis-server weer beschikbaar is (zal hopelijk in de vakantie weer opgelost zijn voor mijn portfolio.

Is het slecht dat ik herbruikbare code gebruik van andere projecten?

**Comment by SilvanDomino** [comment]
Het is juist geweldig dat je zoiets doet! Vooral blijven doen! Iedereen zou dat moeten doen.
Als je bij een javascript bedrijf gaat solliciteren moet je deze opdracht(en) vooral laten zien. 

Het probleem was, de opdracht was voor Unity, het was de bedoeling om een Unity build te maken. Dat was hetgene waar ik op doelde. Ik vermoed tenminste dat het gaat om Proefopdracht 4 van Gainplay Studios.
